### PR TITLE
Pin version of used SDK to workaround of buggy SDK version

### PR DESCRIPTION
**Pull request by leotsarev**
https://github.com/dotnet/sdk/issues/10878
https://github.com/SpecFlowOSS/SpecFlow/issues/1912

### CODE REVIEW

**Comment by SabotageAndi** [comment]
This should not be needed, because we already pin the SDK version.
See https://github.com/SpecFlowOSS/SpecFlow.TestProjectGenerator/blob/4ecbe931ca7e18b6325776fad8ef1cd04add247b/SpecFlow.TestProjectGenerator/FilesystemWriter/NetCoreSdkInfoProvider.cs

**Comment by leotsarev** [comment]
Hmm, for me it's not working w/o my fix. I'll look closer...

**Comment by SabotageAndi** [comment]
I tried it with the current master and all tests worked.

**Comment by leotsarev** [comment]
Sorry for this, now it's working for me probably. I failed to figure why it failed for me in first place.

**Comment by SabotageAndi** [comment]
No problem at all.

**Pull request closed without merging**
